### ISSUE TITLE
AB1 Aufgabe 4

### ISSUE THREAD

**Issue by matthinc** [sweIhm-ws2018-19/skillproject-do-5#1]
Aufgabe 4 in das Wiki einstellen.

**Comment by seanog8** [comment]
Passt alles soweit. 
Das Einzige was mir aufgefallen ist, dass Konto und Kunde 1 bis n Beziehungen haben und Privatkunde/Geschäftskunde 0 bis n zu Adresse. Das würde man wohl im Konstruktor sicherstellen.

**Comment by seanog8** [comment]
Ich frage mich noch ob es Listen sein dürfen oder Arrays sein müssen. In den Folien habe ich jedenfalls nur Arrays gesehen bei solchen Zuweisungen. z.B Folie 51 UML and Modeling

**Comment by bremade** [comment]
Wir benötigen hier eine Datenstruktur, die entweder eine feste oder eine dynamische Anzahl anderer Objekte aufnimmt. Deshalb sind hier Listen besser.
