### ISSUE TITLE
Profil erstellen

### ISSUE THREAD

**Issue by bremade** [sweIhm-ws2018-19/skillproject-do-5#10]
Als Nutzer will ich mein Profil anlegen.

## Akzeptanzkriterien
* induvidueller Name
* Geschlecht
* Alter
* Gewicht
* (Größe)
* (Promillewarnwert)

## Unteraufgaben
- [x] Modellklassen anlegen [Jan]
[Zugehörige Issue](https://github.com/sweIhm-ws2018-19/skillproject-do-5/issues/29)
- [x] Profilregistrierung im Skill [Sean]
[Zugehörige Issue](https://github.com/sweIhm-ws2018-19/skillproject-do-5/issues/30)
- [x] Datenbank aufsetzen [Matthias]
[Zugehörige Issue](https://github.com/sweIhm-ws2018-19/skillproject-do-5/issues/31)
- [x] Datenbankanbindung zum Skill [Matthias]
[Zugehörige Issue](https://github.com/sweIhm-ws2018-19/skillproject-do-5/issues/31)

**Comment by matthinc** [comment]
Für das Modell: https://docs.aws.amazon.com/de_de/amazondynamodb/latest/developerguide/DynamoDBMapper.html

**Comment by bremade** [comment]
Kommentare in den zugehörigen Issues
