### ISSUE TITLE
Promilleabbau abfragen

### ISSUE THREAD

**Issue by bremade** [sweIhm-ws2018-19/skillproject-do-5#11]
Als Nutzer will ich abfragen können, nach welcher Zeit mein Alkoholpegel abgebaut ist.
## Akzeptanzkriterien
* Aus dem Alkoholpegel wird aus der die Zeitspanne berechnet, die benötigt wird, um nüchtern zu werden und mit dem Profilnamen ausgegeben.

**Comment by matthinc** [comment]
Passt
