### ISSUE TITLE
Alkoholpegelwarnung

### ISSUE THREAD

**Issue by bremade** [sweIhm-ws2018-19/skillproject-do-5#12]
Als Nutzer will ich eine Warnung erhalten, falls mein Alkoholpegel über einen gewissen Schwellenwert fällt.
## Akzeptanzkriterien
* Die Warnung wird automatisch nach einer Getränkeeingabe ausgegeben.
* Der Alkoholpegel wird passiv errechnet und es wird nach jeder Getränkeeingabe geprüft ob dieser den Schwellenwert überschreitet.
* Der Schwellenwert ist ein vorgefertigter fester Wert.

**Comment by matthinc** [comment]
Passt
