### ISSUE TITLE
AB1 Aufgabe 5

### ISSUE THREAD

**Issue by matthinc** [sweIhm-ws2018-19/skillproject-do-5#2]
Aufgabe 5 in das Wiki einstellen.

**Comment by matthinc** [comment]
Review:
Einige Dinge müssten noch nachgebessert werden:
- Adresse schreibt man mit einem "d" (Typo)
- Die verwendeten Pfeile wären eher Inheritance als Association
- Die beiden Konten fehlen komplett

**Comment by Joemungandar** [comment]
Nachbesserung erfolgt:

- Rechtschreibfehler "Adresse" verbessert
- Pfeile in Linien ausgetauscht und besser beschriftet
- 2 neue Objekte (Konten) erstellt

**Comment by matthinc** [comment]
Perfekt, sieht gut aus.
