### ISSUE TITLE
Getränk hinzufügen

### ISSUE THREAD

**Issue by seanog8** [sweIhm-ws2018-19/skillproject-do-5#23]
Als Nutzer möchte mitteilen, welches Getränk ich konsumiert habe.
## Akzeptanzkriterien
* ein Getränk aus der Liste der vorhandenen Getränke

## Unteraufgaben
- [x] Alexa-Dialog
- [x] Datenbankanbindung
- [x] Nur erlauben wenn Nutzer ausgewählt ist
- [x] Liste von Getränken/Maßen anlegen [Matthias]

**Comment by bremade** [comment]
Passt auch soweit.
