### ISSUE TITLE
Modellklassen aufsetzen

### ISSUE THREAD

**Issue by bremade** [sweIhm-ws2018-19/skillproject-do-5#29]

**Comment by seanog8** [comment]
Für die Klasse Drink können wir uns noch überlegen, ob wir eine ml Angabe machen oder ob alles über den Int Wert machen.

**Comment by seanog8** [comment]
Sonst siehts gut aus. Müssen halt noch sehen, ob die Userlist unseren Anforderungen für die Sessions später so passt.
